# Generated by Django 4.1 on 2022-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_fixed_membership_fee', models.BooleanField()),
                ('fixed_membership_fee_amount', models.IntegerField()),
            ],
        ),
    ]
