# Generated by Django 4.1 on 2022-08-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unitsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='unit_conf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='units.unitsconfig'),
            preserve_default=False,
        ),
    ]
