# Generated by Django 4.1 on 2022-08-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_units_unit_conf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='unit_conf',
        ),
        migrations.DeleteModel(
            name='UnitsConfig',
        ),
    ]
