# Generated by Django 4.1 on 2022-08-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_remove_units_unit_conf_delete_unitsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='fixed_membership_fee_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='units',
            name='has_fixed_membership_fee',
            field=models.BooleanField(default=False),
        ),
    ]
